version: '3'
services:
  onu:
    build:
      context: ./ONU 
      dockerfile: Dockerfile.ONU
      args:
        oms_server: localhost
        oms_port: 50051
    volumes:
      - ./ONU:/app/ONU
    network_mode: "host"

  continente:
    build:
      context: ./Continente
      dockerfile: Dockerfile.continente
      args:
        oms_server: localhost
        oms_port: 50051
    volumes:
      - ./Continente:/app/Continente
    network_mode: "host"

  oms:
    build:
      context: ./OMS
      dockerfile: Dockerfile.OMS
      args:
        onu_server: localhost
        onu_port: 50070
        data_node1_server: localhost
        data_node1_port: 50052
        data_node2_server: localhost
        data_node2_port: 50053
    volumes:
      - ./OMS:/app/OMS
    network_mode: "host"

  datanode:
    build:
      context: ./Datanodes
      dockerfile: Dockerfile.Datanodes
      args:
        oms_server: localhost
        oms_port: 50051
    volumes:
      - ./Datanodes:/app/Datanodes
    network_mode: "host"
  
