version: '3'
services:
  onu:
    build:
      context: ./ONU 
      dockerfile: Dockerfile.ONU
      args:
        rmq_server: localhost
        rmq_port: 5672
    volumes:
      - ./Valve:/app/Valve
    network_mode: "host"
  regionales1:
    build:
      context: ./Regionales 
      dockerfile: Dockerfile.regionales
      args:
        valve_server: localhost
        rmq_server: localhost
        rmq_port: 5672
        region_name: America
    volumes:
      - ./Regionales:/app/Regionales
    network_mode: "host"
  
  regionales2:
    build:
      context: ./Regionales 
      dockerfile: Dockerfile.regionales
      args:
        valve_server: localhost
        rmq_server: localhost
        rmq_port: 5672
        region_name: Europa
    volumes:
      - ./Regionales:/app/Regionales
    network_mode: "host"
      
  regionales3:
    build:
      context: ./Regionales 
      dockerfile: Dockerfile.regionales
      args:
        valve_server: localhost
        rmq_server: localhost
        rmq_port: 5672
        region_name: Asia
    volumes:
      - ./Regionales:/app/Regionales
    network_mode: "host"
  
  regionales4:
    build:
      context: ./Regionales 
      dockerfile: Dockerfile.regionales
      args:
        valve_server: localhost
        rmq_server: localhost
        rmq_port: 5672
        region_name: Oceania
    volumes:
      - ./Regionales:/app/Regionales
    network_mode: "host"
  
